name: Docker
run-name: compile within docker
on: [push]
jobs:
  compile_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: instalation
        run: |
          sudo apt-get remove containerd.io
          sudo apt install docker.io docker-compose -y
      - name: Run sequence
        run: docker build -t builder .
      - name: image
        run: docker run --name test -t builder ls
      - name: Copy log file
        run: docker cp test:/repo/log.txt ./log.txt
      - name: file
        uses: actions/upload-artifact@v4
        with:
          name: llogs
          path: /home/runner/work/lab08/lab08/log.txt
